name: CI and QA Deployment

on:
  push:
    branches:
      - my-develop

jobs:
  #Triggers CI and QA deployment when a Source branch is merged to my-develop branch.   
  Deploy_CI:
    name: CI Deployment
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/my-develop' }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install Salesforce CLI
      run: |
        npm install sfdx-cli
        node_modules/sfdx-cli/bin/run --version
        node_modules/sfdx-cli/bin/run plugins --core
        
    - name: Update CLI
      run: node_modules/sfdx-cli/bin/run update
      
    - name: Authenticate CI ORG
      run: |
        echo "${SALESFORCE_JWT_SECRET_KEY}" > server.key
        node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid ${{ secrets.CI_CONSUMER_KEY }} --jwtkeyfile server.key --username ${{ secrets.CI_USERNAME}} --instanceurl ${{ secrets.SFDC_SANDBOX_HOST}} 
      env:
        SALESFORCE_JWT_SECRET_KEY: ${{ secrets.SALESFORCE_JWT_SECRET_KEY }}

    - name: CI ORG Deployment
      run: node_modules/sfdx-cli/bin/run force:source:deploy -p force-app/main/default -u ${{ secrets.CI_USERNAME}}	  

  #Triggers when CI deployment is successful, commence QA deployment
  Deploy_QA:
    name: QA Deployment
    needs: Deploy_CI
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/my-develop'}}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install Salesforce CLI
      run: |
        npm install sfdx-cli
        node_modules/sfdx-cli/bin/run --version
        node_modules/sfdx-cli/bin/run plugins --core
      
    - name: Authenticate QA ORG
      run: |
        echo "${SALESFORCE_JWT_SECRET_KEY}" > server.key
        node_modules/sfdx-cli/bin/run force:auth:jwt:grant --clientid ${{ secrets.QA_CONSUMER_KEY }} --jwtkeyfile server.key --username ${{ secrets.QA_USERNAME}} --instanceurl ${{ secrets.SFDC_SANDBOX_HOST}} 
      env:
        SALESFORCE_JWT_SECRET_KEY: ${{ secrets.SALESFORCE_JWT_SECRET_KEY }}

    - name: QA ORG Deployment
      run: node_modules/sfdx-cli/bin/run force:source:deploy -p force-app/main/default -u ${{ secrets.QA_USERNAME}}